jobs:
  - name: job-heyhey-world
    public: true
    plan:
      - task: heyhey-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [heyhey world]
